### ISSUE TITLE
Action not found error

### ISSUE THREAD

**Issue by johnnybenson** [MontyD/package-json-updated-action#4]
Excited to use this action in my workflow, does exactly what I need.

Can't seem to get it to run based on the readme. Wondering if Github's syntax here has changed in the last year and a half.

`uses: ` has a pattern of `{org}/{repo}[/path]@ref`

I tried using the tags, SHAs, nothing is working. Wondering if I'm doing something or if there's a PR I could open to update this action.

Thanks!

```
    - uses: MontyD/package-json-updated-action@1.0.1
    - uses: MontyD/package-json-updated-action@v1.0.1
    - uses: MontyD/package-json-updated-action@v1
    - uses: MontyD/package-json-updated-action@1
    - uses: MontyD/package-json-updated-action@163e4cf588b92507069c3b71cea55f54dacc3e2cd
```

```
name: Client - Tag Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    
    # Nothing seems to work here 
    - uses: MontyD/package-json-updated-action@1.0.1
      id: version-updated
      with:
        path: ./client/package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

### Error following the README
![image](https://user-images.githubusercontent.com/238022/131166867-a6359979-8ebc-4ec9-882a-f1adad16258c.png)

```
Expected format {org}/{repo}[/path]@ref. Actual 'MontyD/package-json-updated-action' Input string was not in a correct format.
```

### Error after fixing the format

![image](https://user-images.githubusercontent.com/238022/131167048-1c5fc7c0-5377-4820-9d7c-960f43a1880e.png)
